---
abstract: 'C<expect/check>-style unit testing with object methods'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  Test2::V0: '0'
  Test::Builder::Tester: '0'
configure_requires:
  Module::Build: '0.4004'
dynamic_config: 1
generated_by: 'Module::Build version 0.4234, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-ExpectAndCheck
provides:
  Test::ExpectAndCheck:
    file: lib/Test/ExpectAndCheck.pm
    version: '0.06'
  Test::ExpectAndCheck::Future:
    file: lib/Test/ExpectAndCheck/Future.pm
    version: '0.06'
requires:
  List::Util: '0'
  Test::Builder: '1.302'
  Test::Deep: '0'
  Test::Future::Deferred: '0'
  perl: '5.014'
resources:
  license: http://dev.perl.org/licenses/
version: '0.06'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
